# Generated by Django 3.0.11 on 2020-12-14 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('branch_hod', models.CharField(max_length=20)),
                ('contact_no', models.CharField(max_length=14)),
                ('mail_id', models.EmailField(default='@gamil.com', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('website', models.URLField(max_length=100)),
                ('type', models.CharField(max_length=15)),
                ('desc', models.TextField()),
                ('no_of_alumni', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=1)),
                ('year_of_grad', models.IntegerField(default=2018)),
                ('mail_id', models.EmailField(default='@gmail.com', max_length=30)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=15)),
                ('gender', models.CharField(default='M', max_length=1)),
                ('year_of_grad', models.IntegerField(default=2018)),
                ('mail_id', models.EmailField(default='@gmail.com', max_length=30)),
                ('work_expirience', models.IntegerField(default=2)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.Branch')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.Company')),
            ],
        ),
    ]
